config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  namespace :admin do
    root to: "application#index"

    resources :projects
  end

  resources :projects




  get "contact", to: "pages#contact"
  get "me", to: "pages#me"
  get "service", to: "pages#service"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_and_belongs_to_many :tags, uniq: true

  attr_accessor :tag_names

  def tag_names=(names)
    @tag_names = names
    @tag_names.split(' ').each do |name|
      self.tags << Tag.find_or_create_by(name: name.upcase)
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!

  def index
    @user = current_user
  end

  protected

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, alert: "Vous devez être administrateur pour avoir accés !"
    end
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  before_action :set_user, only: [:new, :create]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = @user.projects.build
  end

  def create
    @project = @user.projects.build(project_params)
    if @project.save!
      flash[:notice] = "Le projet a bien été créé !"
      redirect_to admin_project_path(@project)
    else
      flash[:alert] = "Le projet n'a pu être créé !"
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Le projet a bien été modifie !"
      redirect_to admin_project_path(@project)
    else
      flash[:alert] = "Le projet n'a pu être modifié !"
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to admin_projects_path
  end

  private

  def set_user
    @user = current_user
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :tag_names, images: [])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def contact
  end

  def me
  end

  def service
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/application/index.html.erb
<div class="admin-app-index-wrapper">

  <h2><%= @user.email %></h2>

  <%= link_to 'Voir mes projets', admin_projects_path, class: "button-nav" %>

</div>

app/views/admin/projects/edit.html.erb
<div class="form-wrapper">
  <div class="form">
    <h2>Modifier le projet</h2>

    <%= form_for [:admin, @project] do |f| %>

      <%= f.text_field :title, placeholder: 'Titre', class: 'form-field' %>

      <%= f.text_area :description, placeholder: 'Description', class: 'form-field' %>

      <%= f.text_field :link, placeholder: 'Lien', class: 'form-field' %>

      <%= f.text_area :tag_names, placeholder: 'Tag', class: 'form-field' %>

      <%= f.label :images %>
      <%= f.file_field :images, :multiple => true %>

      <%= f.submit "Valider", class: 'valid-button' %>

    <% end %>
  </div>
</div>

app/views/admin/projects/index.html.erb
<div class="admin-projects-index-wrapper">
  <div class="top">
    <h2>Mes projets:</h2>
    <%= link_to 'Creer un projet', new_admin_project_path, class: 'button-nav' %>
  </div>

  <div class="projects-list">
    <% if @projects.any? %>
      <% @projects.each_with_index do |project, index| %>
        <%= link_to admin_project_path(project) do %>
          #<%= index %> - <%= project.title %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/projects/new.html.erb
<div class="form-wrapper">
  <div class="form">
    <h2>Créer un projet</h2>

    <%= form_for [:admin, @project] do |f| %>

      <%= f.text_field :title, placeholder: 'Titre', class: 'form-field' %>

      <%= f.text_area :description, placeholder: 'Description', class: 'form-field' %>

      <%= f.text_field :link, placeholder: 'Lien', class: 'form-field' %>

      <%= f.text_area :tag_names, placeholder: 'Tag', class: 'form-field' %>

      <%= f.label :images %>
      <%= f.file_field :images, :multiple => true %>

      <%= f.submit "Valider", class: 'valid-button' %>

    <% end %>
  </div>
</div>

app/views/admin/projects/show.html.erb
<div class="admin-project-show-wrapper">

  <h2><%= @project.title %></h2>
  <p><%= @project.description %></p>
  <p><%= @project.link %></p>
  <% if @project.tags.any? %>
    <% @project.tags.each do |tag| %>
      <%= tag.name %>
    <% end %>
  <% end %>
  <% if @project.images.any? %>
    <% @project.images.each do |image| %>
      <%= cl_image_tag(image.try(:key)) %>
    <% end %>
  <% end %>

  <div class="links">
    <%= link_to 'Modifier le projet', edit_admin_project_path(@project), class: 'button-nav' %>
    <%= link_to 'Supprimer le projet', admin_project_path(@project), data: { confirm: 'Etes vous sur?' }, method: :delete, class: 'button-nav' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdrienPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag 'logo.png' %>
  </head>

  <body>

    <div class="nav-bar-wrapper">
      <div class="nav-bar">
        <%= link_to root_path do %>
          <h4>ADRIEN</h4>
        <% end %>
        <div class="nav-link">
          <%= link_to 'A propos', me_path  %>
          <%= link_to 'Mes services', service_path  %>
          <%= link_to 'Mes réalisations', projects_path %>
          <%= link_to 'Me contacter', contact_path %>
        </div>
        <div class="social-link">
          <a href="tel:0679093818"><i class="fas fa-phone"></i></a>
          <a href="mailto:adrien-barbier@hotmail.fr"><i class="fas fa-envelope"></i></a>
          <a href="https://www.linkedin.com/in/adrien-barbier-5b479598/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
        </div>
      </div>
    </div>

      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>">
          <%= message %>
        </div>
      <% end %>


      <%= yield %>



  </body>
</html>

app/views/pages/contact.html.erb
<div class="contact-page-wrapper">
  <div class="top">
    <h2>Une question ? Besoin d'un devis ?</h2>
    <h2>Contactez moi:</h2>
  </div>

  <div class="mail">
    <h4>Par mail:</h4>
    <p>adrien-barbier@hotmail.fr</p>
  </div>

  <div class="phone">
    <h4>Par téléphone:</h4>
    <p>06 79 09 38 18</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-wrapper">
  <div class="home-title">
    <h1>Développeur</h1>
    <h1 id="orange">web</h1>
  </div>
  <div class="content">
    <div class="content__container">
      <ul class="content__container__list">
        <li class="content__container__list__item">Spécialisé dans le développement de site internet sur-mesure</li>
        <li class="content__container__list__item">Capable de développer des applications web</li>
        <li class="content__container__list__item">Qui vous guide et vous accompagne dans vos choix</li>
        <li class="content__container__list__item">Qui s'adapte rapidement et a le goût le challenge</li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/me.html.erb
<div class="me-page-wrapper">
  <%= image_tag "photo1.jpg" %>
  <div class="description">
    <h3>Adrien Barbier</h3>
    <p>Après un passage dans l’industrie en tant qu’ingénieur projet, et plusieurs expériences entrepreneuriales, j’ai décidé de me lancer dans le développement web. Pourquoi ? Le web c’est quand même beaucoup plus fun ! Et il n’y a aucune limite à ce que l’on peut développer !</p>
    <p>J’ai pour passion de donner vie à vos envies, que ce soit en solo ou en équipe. Ouvert à tout nouveau challenge, je suis à l’écoute pour discuter de la manière dont je peux être utile à votre projet !
Préparez-vous à transformer vos idées en réalité !</p>
  </div>

</div>

app/views/pages/service.html.erb
<div class="service-page-wrapper">

  <div class="service">
    <div class="description">
      <h2>1. Conception</h2>
      <p>La conception d’un produit est une étape primordiale. Elle permet de poser des bases solides, et d’anticiper au maximum les possibles futurs aléas du projet. C’est à cette étape qu’il faut se poser un maximum de questions afin de pouvoir cibler l’utilisateur, et développer une application ergonomique, intuitive, sur laquelle il pourra trouver rapidement l’information qu’il cherche.</p>
    </div>
    <%= image_tag "conception.svg" %>
  </div>

  <div class="line"></div>

  <div class="service" id="right">
    <%= image_tag "design.svg" %>
    <div class="description">
      <h2>2. Design</h2>
      <p>Le design est la première interaction avec l’utilisateur, il doit donc être adapté et soigné pour que l’expérience utilisateur soit la meilleure possible. C’est aussi ce qui va vous différencier de vos concurrents, c’est en quelque sorte votre image de marque.</p>
    </div>
  </div>

  <div class="line" id="right"></div>

  <div class="service">
    <div class="description">
      <h2>3. Développement</h2>
      <p>C’est à cette étape que le projet prend forme. Je m’adapte le plus possible à vos besoins en utilisant les technologies qui correspondent le mieux à vos projets. Le but étant de développer une application web ou un site internet facile d’utilisation pour vos utilisateurs comme pour vous !</p>
    </div>
    <%= image_tag "developpement.svg" %>
  </div>


</div>

app/views/projects/index.html.erb
<div class="projects-index-wrapper">
  <h2>Mes réalisations:</h2>

  <div class="projects-index">
    <% if @projects.any? %>
      <% @projects.each do |project| %>
        <div class="project">
          <%= link_to project_path(project) do %>
            <% if project.images.any? %>
              <%= cl_image_tag(project.images[0].try(:key)) %>
            <% end %>
            <div class="title">
              <h3><%= project.title %></h3>
            </div>
          <% end %>
        </div>

      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="project-show-wrapper">
  <% if @project.images.any? %>
    <%= cl_image_tag(@project.images[1].try(:key)) %>
  <% end %>
  <div class="project-info">
    <div class="description">
      <h2><%= @project.title %></h2>
      <p> <%= @project.description %> </p>
    </div>
    <div class="stack">
      <h4>Techniques utilisées:</h4>
      <% if @project.tags.any? %>
        <ul>
          <% @project.tags.each do |tag| %>
            <li>
              <%= tag.name %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <a href="<%= @project.link %>" class="button-link" target="_blank">Visiter le site internet</a>
  </div>
</div>